import type { PhysiqueCategory, PhysiqueChoice, PhysiqueEffect, PhysiqueOption, PhysiqueTier } from '../types';

export const PHYSIQUE_TIERS: PhysiqueTier[] = ['凡体', '灵体', '道体', '仙体'];

export const PHYSIQUE_CATEGORIES: PhysiqueCategory[] = [
  '无特效',
  '战斗',
  '生产',
  '修炼',
  '突破',
  '领悟',
  '综合',
  '叙述',
  'NSFW',
];

/** 各等级的三维总和 S（取角色生成规则中的高值） */
export const PHYSIQUE_TIER_S: Record<PhysiqueTier, number> = {
  凡体: 30,
  灵体: 50,
  道体: 75,
  仙体: 100,
};

/** 各等级开局点数消耗 */
export const PHYSIQUE_TIER_COST: Record<PhysiqueTier, number> = {
  凡体: 0,
  灵体: 3,
  道体: 9,
  仙体: 15,
};

export const PHYSIQUE_TIER_INTRO: Record<PhysiqueTier, string> = {
  凡体: '普通修士，根基平凡。',
  灵体: '大能修士，微具异象。',
  道体: '气运之子，罕见异体。',
  仙体: '真仙血脉，夺天地造化。',
};

/**
 * 预设体质清单。
 * 数据同步自 Cultivation-Card-Game/Doc/预设体质清单.csv；
 * 分类与五行只用于开局界面筛选，不额外推导规则效果。
 */
export const physiques: PhysiqueOption[] = [
  {
    id: 'phy-fan-gu',
    name: '凡骨',
    tier: '凡体',
    category: '无特效',
    五行: '土',
    subtitle: '无特效',
    cost: 0,
    悟性: 10,
    根骨: 10,
    气感: 10,
    glyph: '土',
    tags: ['无特效', '土'],
  },
  {
    id: 'phy-fan-hui',
    name: '灵慧凡躯',
    tier: '凡体',
    category: '无特效',
    五行: '水',
    subtitle: '无特效',
    cost: 0,
    悟性: 14,
    根骨: 8,
    气感: 8,
    glyph: '水',
    tags: ['无特效', '水'],
  },
  {
    id: 'phy-fan-zhuo',
    name: '朴拙凡躯',
    tier: '凡体',
    category: '无特效',
    五行: '金',
    subtitle: '无特效',
    cost: 0,
    悟性: 8,
    根骨: 14,
    气感: 8,
    glyph: '金',
    tags: ['无特效', '金'],
  },
  {
    id: 'phy-fan-min',
    name: '灵敏凡躯',
    tier: '凡体',
    category: '无特效',
    五行: '木',
    subtitle: '无特效',
    cost: 0,
    悟性: 8,
    根骨: 8,
    气感: 14,
    glyph: '木',
    tags: ['无特效', '木'],
  },
  {
    id: 'phy-man-li',
    name: '蛮力之躯',
    tier: '灵体',
    category: '战斗',
    五行: '土',
    subtitle: '战斗',
    cost: 3,
    悟性: 14,
    根骨: 22,
    气感: 14,
    效果: [{ name: '蛮力', value: '战斗中，使用徒手或重兵器进行近身攻击时，攻击力视为+15%' }],
    glyph: '土',
    tags: ['战斗', '土'],
  },
  {
    id: 'phy-chi-yan',
    name: '赤焰灵体',
    tier: '灵体',
    category: '战斗',
    五行: '火',
    subtitle: '战斗',
    cost: 3,
    悟性: 16,
    根骨: 16,
    气感: 18,
    效果: [
      { name: '亲火', value: '战斗中，使用火属性功法时，攻击力视为+15%' },
      { name: '御寒', value: '免疫不高于自身境界的严寒环境影响' },
    ],
    glyph: '火',
    tags: ['战斗', '火'],
  },
  {
    id: 'phy-han-shuang',
    name: '寒霜玉体',
    tier: '灵体',
    category: '战斗',
    五行: '水',
    subtitle: '战斗',
    cost: 3,
    悟性: 16,
    根骨: 14,
    气感: 20,
    效果: [
      { name: '寒脉', value: '战斗中，使用水或冰属性功法时，攻击力视为+15%' },
      { name: '畏炎', value: '战斗中，受到火属性攻击时，减免视为-10%' },
    ],
    glyph: '水',
    tags: ['战斗', '水'],
  },
  {
    id: 'phy-xuan-gui',
    name: '玄龟灵体',
    tier: '灵体',
    category: '战斗',
    五行: '土',
    subtitle: '战斗',
    cost: 3,
    悟性: 12,
    根骨: 24,
    气感: 14,
    效果: [
      { name: '龟甲', value: '战斗中，受到近身攻击时，减免视为+10%' },
      { name: '迟重', value: '战斗中，闪避视为-1' },
    ],
    glyph: '土',
    tags: ['战斗', '土'],
  },
  {
    id: 'phy-zhu-que',
    name: '朱雀灵躯',
    tier: '灵体',
    category: '战斗',
    五行: '火',
    subtitle: '战斗',
    cost: 3,
    悟性: 15,
    根骨: 17,
    气感: 18,
    效果: [
      { name: '火羽', value: '战斗中，使用火属性功法时，攻击力视为+10%' },
      {
        name: '浴火余烬',
        value: '战斗中，每场战斗首次受到火属性攻击后，于本轮结束时气血恢复量视为该次实际损失气血的15%',
      },
    ],
    glyph: '火',
    tags: ['战斗', '火'],
  },
  {
    id: 'phy-风行灵体',
    name: '风行灵体',
    tier: '灵体',
    category: '战斗',
    五行: '木',
    subtitle: '战斗',
    cost: 3,
    悟性: 15,
    根骨: 15,
    气感: 20,
    效果: [
      { name: '风行', value: '战斗中，使用身法时，遁速视为+15%' },
      { name: '借风', value: '战斗中，第一轮的闪避视为+1' },
    ],
    glyph: '木',
    tags: ['战斗', '木'],
  },
  {
    id: 'phy-炎阳血躯',
    name: '炎阳血躯',
    tier: '灵体',
    category: '战斗',
    五行: '火',
    subtitle: '战斗',
    cost: 3,
    悟性: 14,
    根骨: 21,
    气感: 15,
    效果: [
      { name: '烈血', value: '战斗中，气血低于50%且使用火属性功法时，攻击力视为+15%' },
      { name: '耐灼', value: '战斗中，受到火属性攻击时，减免视为+10%' },
    ],
    glyph: '火',
    tags: ['战斗', '火'],
  },
  {
    id: 'phy-地脉石胎',
    name: '地脉石胎',
    tier: '灵体',
    category: '战斗',
    五行: '土',
    subtitle: '战斗',
    cost: 3,
    悟性: 13,
    根骨: 23,
    气感: 14,
    效果: [{ name: '石肤', value: '战斗中，受到近身攻击时，减免视为+10%' }],
    glyph: '土',
    tags: ['战斗', '土'],
  },
  {
    id: 'phy-幽冥灵体',
    name: '幽冥灵体',
    tier: '灵体',
    category: '战斗',
    五行: '阴',
    subtitle: '战斗',
    cost: 3,
    悟性: 18,
    根骨: 14,
    气感: 18,
    效果: [
      { name: '幽行', value: '战斗中，使用阴属性功法时，攻击力视为+15%' },
      { name: '冥定', value: '战斗中，每场战斗首次遭受同境及以下敌人施加的恐惧时，免疫该次恐惧效果' },
    ],
    glyph: '阴',
    tags: ['战斗', '阴'],
  },
  {
    id: 'phy-明光净体',
    name: '明光净体',
    tier: '灵体',
    category: '战斗',
    五行: '阳',
    subtitle: '战斗',
    cost: 3,
    悟性: 18,
    根骨: 16,
    气感: 16,
    效果: [
      { name: '明光', value: '战斗中，使用阳属性功法时，攻击力视为+10%' },
      { name: '净秽', value: '战斗中，每场战斗首次遭受同境及以下敌人施加的侵蚀时，免疫该次侵蚀效果' },
    ],
    glyph: '阳',
    tags: ['战斗', '阳'],
  },
  {
    id: 'phy-潮汐灵体',
    name: '潮汐灵体',
    tier: '灵体',
    category: '战斗',
    五行: '水',
    subtitle: '战斗',
    cost: 3,
    悟性: 17,
    根骨: 15,
    气感: 18,
    效果: [
      { name: '潮息', value: '战斗中，使用水属性功法时，灵气消耗视为-10%' },
      { name: '回潮', value: '战斗中，每场战斗首次气血低于50%时，下一次获得的气血恢复量视为+15%' },
    ],
    glyph: '水',
    tags: ['战斗', '水'],
  },
  {
    id: 'phy-山岳灵体',
    name: '山岳灵体',
    tier: '灵体',
    category: '战斗',
    五行: '土',
    subtitle: '战斗',
    cost: 3,
    悟性: 12,
    根骨: 25,
    气感: 13,
    效果: [
      { name: '山躯', value: '战斗中，受到近身攻击时，减免视为+12%' },
      { name: '沉身', value: '战斗中，闪避视为-1' },
    ],
    glyph: '土',
    tags: ['战斗', '土'],
  },
  {
    id: 'phy-琉璃净体',
    name: '琉璃净体',
    tier: '灵体',
    category: '战斗',
    五行: '混沌',
    subtitle: '战斗',
    cost: 3,
    悟性: 20,
    根骨: 14,
    气感: 16,
    效果: [
      { name: '澄心', value: '战斗中，每场战斗首次遭受同境及以下敌人施加的幻觉时，免疫该次幻觉效果' },
      { name: '净识', value: '战斗中，使用神识功法时，灵气消耗视为-10%' },
    ],
    glyph: '混沌',
    tags: ['战斗', '混沌'],
  },
  {
    id: 'phy-天蚕灵体',
    name: '天蚕灵体',
    tier: '灵体',
    category: '战斗',
    五行: '木',
    subtitle: '战斗',
    cost: 3,
    悟性: 16,
    根骨: 19,
    气感: 15,
    效果: [
      { name: '柔筋', value: '战斗中，受到近身攻击时，闪避视为+1' },
      { name: '绵劲', value: '战斗中，使用护体功法时，减免视为+10%' },
    ],
    glyph: '木',
    tags: ['战斗', '木'],
  },
  {
    id: 'phy-血煞灵体',
    name: '血煞灵体',
    tier: '灵体',
    category: '战斗',
    五行: '阴',
    subtitle: '战斗',
    cost: 3,
    悟性: 14,
    根骨: 22,
    气感: 14,
    效果: [
      { name: '血战', value: '战斗中，气血低于50%且进行近身攻击时，攻击力视为+15%' },
      { name: '煞脉', value: '战斗中，气血恢复量视为-10%' },
    ],
    glyph: '阴',
    tags: ['战斗', '阴'],
  },
  {
    id: 'phy-流光灵体',
    name: '流光灵体',
    tier: '灵体',
    category: '战斗',
    五行: '金',
    subtitle: '战斗',
    cost: 3,
    悟性: 18,
    根骨: 14,
    气感: 18,
    效果: [
      { name: '流光御器', value: '战斗中，每场战斗首次使用法宝进行攻击检定时，命中视为+1' },
      { name: '轻御', value: '战斗中，使用法宝攻击时，灵气消耗视为-10%' },
    ],
    glyph: '金',
    tags: ['战斗', '金'],
  },
  {
    id: 'phy-蜃梦灵体',
    name: '蜃梦灵体',
    tier: '灵体',
    category: '战斗',
    五行: '水',
    subtitle: '战斗',
    cost: 3,
    悟性: 20,
    根骨: 12,
    气感: 18,
    效果: [
      { name: '蜃景', value: '战斗中，进行幻术意图对抗时，幻术视为+15%' },
      { name: '识梦', value: '战斗中，每场战斗首次作为幻术意图对抗的守方时，幻术视为+10%' },
    ],
    glyph: '水',
    tags: ['战斗', '水'],
  },
  {
    id: 'phy-tian-lei',
    name: '天雷殛体',
    tier: '道体',
    category: '战斗',
    五行: '火',
    subtitle: '战斗',
    cost: 9,
    悟性: 22,
    根骨: 26,
    气感: 27,
    效果: [
      { name: '雷殛', value: '战斗中，使用雷属性功法时，攻击力视为+20%' },
      { name: '淬雷', value: '战斗中，受到雷属性攻击时，减免视为+20%' },
    ],
    glyph: '火',
    tags: ['战斗', '火'],
  },
  {
    id: 'phy-bu-mie',
    name: '不灭金身',
    tier: '道体',
    category: '战斗',
    五行: '金',
    subtitle: '战斗',
    cost: 9,
    悟性: 22,
    根骨: 33,
    气感: 20,
    效果: [
      { name: '金身', value: '战斗中，受到近身攻击时，减免视为+20%' },
      { name: '辟邪', value: '战斗中，遭受同境及以下邪祟施加的恐惧或侵蚀时，免疫恐惧与侵蚀效果' },
    ],
    glyph: '金',
    tags: ['战斗', '金'],
  },
  {
    id: 'phy-xuan-wu',
    name: '玄武不动体',
    tier: '道体',
    category: '战斗',
    五行: '水',
    subtitle: '战斗',
    cost: 9,
    悟性: 22,
    根骨: 30,
    气感: 23,
    效果: [
      { name: '不动', value: '战斗中，受到远程攻击或咒法攻击时，减免视为+20%' },
      { name: '镇厄', value: '战斗中，每场战斗首次遭受同境及以下敌人施加的封禁或诅咒时，免疫该次封禁或诅咒效果' },
    ],
    glyph: '水',
    tags: ['战斗', '水'],
  },
  {
    id: 'phy-庚金战体',
    name: '庚金战体',
    tier: '道体',
    category: '战斗',
    五行: '金',
    subtitle: '战斗',
    cost: 9,
    悟性: 21,
    根骨: 31,
    气感: 23,
    效果: [
      { name: '庚锋', value: '战斗中，使用金属性功法或金属兵器时，攻击力视为+20%' },
      { name: '破甲', value: '战斗中，进行近身攻击时，穿透视为+20%' },
    ],
    glyph: '金',
    tags: ['战斗', '金'],
  },
  {
    id: 'phy-瀚海归墟体',
    name: '瀚海归墟体',
    tier: '道体',
    category: '战斗',
    五行: '水',
    subtitle: '战斗',
    cost: 9,
    悟性: 26,
    根骨: 22,
    气感: 27,
    效果: [
      { name: '归墟', value: '战斗中，使用水属性功法时，攻击力视为+20%' },
      { name: '纳海', value: '战斗中，使用水属性功法时，灵气消耗视为-15%' },
    ],
    glyph: '水',
    tags: ['战斗', '水'],
  },
  {
    id: 'phy-焚天炎神体',
    name: '焚天炎神体',
    tier: '道体',
    category: '战斗',
    五行: '火',
    subtitle: '战斗',
    cost: 9,
    悟性: 24,
    根骨: 28,
    气感: 23,
    效果: [
      { name: '焚天', value: '战斗中，使用火属性功法时，攻击力视为+20%' },
      { name: '炎神', value: '免疫不高于自身境界的严寒环境影响' },
      { name: '炎血', value: '战斗中，遭受同境及以下来源施加的冻伤时，免疫该次冻伤效果' },
    ],
    glyph: '火',
    tags: ['战斗', '火'],
  },
  {
    id: 'phy-厚土镇岳体',
    name: '厚土镇岳体',
    tier: '道体',
    category: '战斗',
    五行: '土',
    subtitle: '战斗',
    cost: 9,
    悟性: 20,
    根骨: 34,
    气感: 21,
    效果: [
      { name: '镇岳', value: '战斗中，受到近身攻击时，减免视为+20%' },
      { name: '不移', value: '战斗中，双足着地时，命中视为+1' },
    ],
    glyph: '土',
    tags: ['战斗', '土'],
  },
  {
    id: 'phy-昊阳明净体',
    name: '昊阳明净体',
    tier: '道体',
    category: '战斗',
    五行: '阳',
    subtitle: '战斗',
    cost: 9,
    悟性: 26,
    根骨: 25,
    气感: 24,
    效果: [
      { name: '昊阳', value: '战斗中，使用阳属性功法时，攻击力视为+20%' },
      {
        name: '明净',
        value: '战斗中，每场战斗首次遭受同境及以下敌人施加的魅惑、恐惧或侵蚀时，免疫该次魅惑、恐惧或侵蚀效果',
      },
    ],
    glyph: '阳',
    tags: ['战斗', '阳'],
  },
  {
    id: 'phy-两仪道胎',
    name: '两仪道胎',
    tier: '道体',
    category: '战斗',
    五行: '混沌',
    subtitle: '战斗',
    cost: 9,
    悟性: 29,
    根骨: 22,
    气感: 24,
    效果: [
      { name: '两仪轮转', value: '战斗中，前后相邻两次所用功法分别为阴与阳时，第二次功法的攻击力视为+20%' },
      { name: '阴阳互济', value: '战斗中，使用阴或阳属性功法时，灵气消耗视为-10%' },
    ],
    glyph: '混沌',
    tags: ['战斗', '混沌'],
  },
  {
    id: 'phy-北冥寒髓体',
    name: '北冥寒髓体',
    tier: '道体',
    category: '战斗',
    五行: '水',
    subtitle: '战斗',
    cost: 9,
    悟性: 25,
    根骨: 27,
    气感: 23,
    效果: [
      { name: '北冥寒息', value: '战斗中，使用水或冰属性功法时，攻击力视为+20%' },
      { name: '寒髓', value: '战斗中，受到火属性攻击时，减免视为-10%' },
    ],
    glyph: '水',
    tags: ['战斗', '水'],
  },
  {
    id: 'phy-无垢道体',
    name: '无垢道体',
    tier: '道体',
    category: '战斗',
    五行: '阳',
    subtitle: '战斗',
    cost: 9,
    悟性: 29,
    根骨: 23,
    气感: 23,
    效果: [
      { name: '无垢', value: '战斗中，每场战斗首次遭受同境及以下敌人施加的毒素或诅咒时，免疫该次毒素或诅咒效果' },
      { name: '清净', value: '战斗中，使用丹药恢复气血时，气血恢复量视为+15%' },
    ],
    glyph: '阳',
    tags: ['战斗', '阳'],
  },
  {
    id: 'phy-幽梦道体',
    name: '幽梦道体',
    tier: '道体',
    category: '战斗',
    五行: '阴',
    subtitle: '战斗',
    cost: 9,
    悟性: 30,
    根骨: 19,
    气感: 26,
    效果: [
      { name: '幽梦', value: '战斗中，进行幻术意图对抗时，幻术视为+20%' },
      { name: '梦醒', value: '战斗中，每场战斗首次遭受同境及以下敌人施加的魅惑时，免疫该次魅惑效果' },
    ],
    glyph: '阴',
    tags: ['战斗', '阴'],
  },
  {
    id: 'phy-星辰道体',
    name: '星辰道体',
    tier: '道体',
    category: '战斗',
    五行: '混沌',
    subtitle: '战斗',
    cost: 9,
    悟性: 28,
    根骨: 24,
    气感: 23,
    效果: [
      { name: '星识', value: '战斗中，进行神识意图对抗时，神识视为+18%' },
      { name: '列宿成阵', value: '战斗中，自身参与结成的阵法灵气容量视为+18%' },
    ],
    glyph: '混沌',
    tags: ['战斗', '混沌'],
  },
  {
    id: 'phy-万象灵胎',
    name: '万象灵胎',
    tier: '道体',
    category: '战斗',
    五行: '混沌',
    subtitle: '战斗',
    cost: 9,
    悟性: 27,
    根骨: 23,
    气感: 25,
    效果: [
      { name: '万象', value: '战斗中，使用与上一轮不同五行的攻击功法时，攻击力视为+15%' },
      { name: '化气', value: '战斗中，使用非心法类功法时，灵气消耗视为-10%' },
    ],
    glyph: '混沌',
    tags: ['战斗', '混沌'],
  },
  {
    id: 'phy-修罗战体',
    name: '修罗战体',
    tier: '道体',
    category: '战斗',
    五行: '阴',
    subtitle: '战斗',
    cost: 9,
    悟性: 20,
    根骨: 35,
    气感: 20,
    效果: [
      { name: '修罗战意', value: '战斗中，每击败一名敌人，攻击力视为+5%，最多视为+20%，战斗结束后清除' },
      { name: '血斗', value: '战斗中，气血低于50%且受到近身攻击时，减免视为+15%' },
    ],
    glyph: '阴',
    tags: ['战斗', '阴'],
  },
  {
    id: 'phy-tai-chu',
    name: '太初真魔体',
    tier: '仙体',
    category: '战斗',
    五行: '阴',
    subtitle: '战斗',
    cost: 15,
    悟性: 30,
    根骨: 38,
    气感: 32,
    效果: [
      { name: '魔躯', value: '战斗中，使用阴或火属性功法时，攻击力视为+25%' },
      { name: '万邪不侵', value: '战斗中，遭受同境及以下敌人施加的魅惑、恐惧或侵蚀时，免疫魅惑、恐惧与侵蚀效果' },
    ],
    glyph: '阴',
    tags: ['战斗', '阴'],
  },
  {
    id: 'phy-xu-kong',
    name: '虚空幻灭体',
    tier: '仙体',
    category: '战斗',
    五行: '混沌',
    subtitle: '战斗',
    cost: 15,
    悟性: 38,
    根骨: 28,
    气感: 34,
    效果: [
      { name: '虚相', value: '战斗中，每场战斗首次成为攻击目标时，闪避视为+3' },
      { name: '幻灭', value: '战斗中，进行神识或幻术意图对抗时，对应技艺视为+25%' },
    ],
    glyph: '混沌',
    tags: ['战斗', '混沌'],
  },
  {
    id: 'phy-混沌道体',
    name: '混沌道体',
    tier: '仙体',
    category: '战斗',
    五行: '混沌',
    subtitle: '战斗',
    cost: 15,
    悟性: 34,
    根骨: 33,
    气感: 33,
    效果: [
      { name: '混沌衍法', value: '战斗中，使用金、木、水、火或土属性功法时，攻击力视为+25%' },
      { name: '归一', value: '战斗中，使用功法时，灵气消耗视为-20%' },
    ],
    glyph: '混沌',
    tags: ['战斗', '混沌'],
  },
  {
    id: 'phy-万古青莲体',
    name: '万古青莲体',
    tier: '仙体',
    category: '战斗',
    五行: '木',
    subtitle: '战斗',
    cost: 15,
    悟性: 36,
    根骨: 32,
    气感: 32,
    效果: [
      { name: '青莲生机', value: '战斗中，气血恢复量视为+30%' },
      { name: '莲心不染', value: '战斗中，遭受同境及以下敌人施加的毒素、魅惑或侵蚀时，免疫毒素、魅惑与侵蚀效果' },
    ],
    glyph: '木',
    tags: ['战斗', '木'],
  },
  {
    id: 'phy-先天圣灵体',
    name: '先天圣灵体',
    tier: '仙体',
    category: '战斗',
    五行: '阳',
    subtitle: '战斗',
    cost: 15,
    悟性: 35,
    根骨: 34,
    气感: 31,
    效果: [
      { name: '圣灵之光', value: '战斗中，使用阳属性功法时，攻击力视为+25%' },
      { name: '诸邪退散', value: '战斗中，战斗开始时，解除一个由同境及以下敌人施加的负面状态效果' },
    ],
    glyph: '阳',
    tags: ['战斗', '阳'],
  },
  {
    id: 'phy-九幽冥王体',
    name: '九幽冥王体',
    tier: '仙体',
    category: '战斗',
    五行: '阴',
    subtitle: '战斗',
    cost: 15,
    悟性: 33,
    根骨: 37,
    气感: 30,
    效果: [
      { name: '冥王敕令', value: '战斗中，使用阴属性功法时，攻击力视为+30%' },
      { name: '九幽威仪', value: '战斗中，免疫同境及以下敌人施加的恐惧、魅惑与侵蚀效果' },
    ],
    glyph: '阴',
    tags: ['战斗', '阴'],
  },
  {
    id: 'phy-元磁神体',
    name: '元磁神体',
    tier: '仙体',
    category: '战斗',
    五行: '金',
    subtitle: '战斗',
    cost: 15,
    悟性: 32,
    根骨: 36,
    气感: 32,
    效果: [
      { name: '元磁御器', value: '战斗中，使用金属法宝攻击时，攻击力视为+30%' },
      { name: '磁极回环', value: '战斗中，使用御物功法或法宝攻击时，灵气消耗视为-20%' },
    ],
    glyph: '金',
    tags: ['战斗', '金'],
  },
  {
    id: 'phy-太虚鲲鹏体',
    name: '太虚鲲鹏体',
    tier: '仙体',
    category: '战斗',
    五行: '水',
    subtitle: '战斗',
    cost: 15,
    悟性: 34,
    根骨: 34,
    气感: 32,
    效果: [
      { name: '鲲鹏极速', value: '战斗中，使用身法时，遁速视为+30%' },
      { name: '太虚挪移', value: '战斗中，每场战斗首次成为攻击目标时，闪避视为+3' },
    ],
    glyph: '水',
    tags: ['战斗', '水'],
  },
  {
    id: 'phy-涅槃凤凰体',
    name: '涅槃凤凰体',
    tier: '仙体',
    category: '战斗',
    五行: '火',
    subtitle: '战斗',
    cost: 15,
    悟性: 34,
    根骨: 38,
    气感: 28,
    效果: [
      { name: '凤凰真火', value: '战斗中，使用火属性功法时，攻击力视为+25%' },
      { name: '涅槃', value: '战斗中，每场战斗首次气血低于25%时，于本轮结束时气血恢复量视为气血上限的30%' },
    ],
    glyph: '火',
    tags: ['战斗', '火'],
  },
  {
    id: 'phy-万岳祖龙体',
    name: '万岳祖龙体',
    tier: '仙体',
    category: '战斗',
    五行: '土',
    subtitle: '战斗',
    cost: 15,
    悟性: 29,
    根骨: 43,
    气感: 28,
    效果: [
      { name: '祖龙之力', value: '战斗中，使用徒手或近身攻击时，攻击力视为+30%' },
      { name: '万岳龙鳞', value: '战斗中，受到近身攻击时，减免视为+25%' },
      { name: '镇兽', value: '战斗中，面对同境及以下敌方灵兽时，敌方灵兽第一轮的命中视为-3' },
    ],
    glyph: '土',
    tags: ['战斗', '土'],
  },
  {
    id: 'phy-mu-ling',
    name: '木灵青躯',
    tier: '灵体',
    category: '生产',
    五行: '木',
    subtitle: '生产',
    cost: 3,
    悟性: 14,
    根骨: 18,
    气感: 18,
    效果: [
      { name: '青木亲和', value: '进行培育或医术判定时，对应技艺+10%' },
      { name: '回春', value: '战斗外获得的气血恢复量+15%' },
    ],
    glyph: '木',
    tags: ['生产', '木'],
  },
  {
    id: 'phy-离火炉心',
    name: '离火炉心',
    tier: '灵体',
    category: '生产',
    五行: '火',
    subtitle: '生产',
    cost: 3,
    悟性: 18,
    根骨: 17,
    气感: 15,
    效果: [
      { name: '炉心', value: '进行炼丹或炼器判定时，火焰加值+10%' },
      { name: '火候', value: '首次生产火属性配方成功时，技艺获得值+10%' },
    ],
    glyph: '火',
    tags: ['生产', '火'],
  },
  {
    id: 'phy-丹霞药胎',
    name: '丹霞药胎',
    tier: '灵体',
    category: '生产',
    五行: '火',
    subtitle: '生产',
    cost: 3,
    悟性: 18,
    根骨: 15,
    气感: 17,
    效果: [
      { name: '丹霞炉心', value: '进行炼丹生产时，炼丹技艺+10%' },
      { name: '胎火', value: '进行炼丹生产时，火焰加值+10%' },
    ],
    glyph: '火',
    tags: ['生产', '火'],
  },
  {
    id: 'phy-百工巧体',
    name: '百工巧体',
    tier: '灵体',
    category: '生产',
    五行: '金',
    subtitle: '生产',
    cost: 3,
    悟性: 20,
    根骨: 14,
    气感: 16,
    效果: [
      { name: '巧手', value: '进行炼器或制符生产时，对应技艺+10%' },
      { name: '精工', value: '首次成功生产炼器或制符配方时，对应技艺获得值+10%' },
    ],
    glyph: '金',
    tags: ['生产', '金'],
  },
  {
    id: 'phy-青帝长生体',
    name: '青帝长生体',
    tier: '道体',
    category: '生产',
    五行: '木',
    subtitle: '生产',
    cost: 9,
    悟性: 27,
    根骨: 25,
    气感: 23,
    效果: [
      { name: '青帝生机', value: '战斗外获得的气血恢复量+20%' },
      { name: '草木宗师', value: '进行培育或医术判定时，对应技艺+20%' },
    ],
    glyph: '木',
    tags: ['生产', '木'],
  },
  {
    id: 'phy-大地母胎',
    name: '大地母胎',
    tier: '道体',
    category: '生产',
    五行: '土',
    subtitle: '生产',
    cost: 9,
    悟性: 24,
    根骨: 29,
    气感: 22,
    效果: [
      { name: '地母生息', value: '战斗外获得的气血恢复量+20%' },
      { name: '厚植', value: '进行培育判定时，培育技艺+20%' },
    ],
    glyph: '土',
    tags: ['生产', '土'],
  },
  {
    id: 'phy-符骨道体',
    name: '符骨道体',
    tier: '道体',
    category: '生产',
    五行: '木',
    subtitle: '生产',
    cost: 9,
    悟性: 28,
    根骨: 21,
    气感: 26,
    效果: [
      { name: '符骨', value: '进行制符生产时，制符技艺+20%' },
      { name: '衍符', value: '制符成功时，符箓单份产出+1' },
    ],
    glyph: '木',
    tags: ['生产', '木'],
  },
  {
    id: 'phy-天工炉鼎体',
    name: '天工炉鼎体',
    tier: '道体',
    category: '生产',
    五行: '土',
    subtitle: '生产',
    cost: 9,
    悟性: 24,
    根骨: 30,
    气感: 21,
    效果: [
      { name: '器胎', value: '进行炼器或制傀生产时，炼器技艺+20%' },
      { name: '内炉', value: '进行炼器或制傀生产时，火焰加值+20%' },
    ],
    glyph: '土',
    tags: ['生产', '土'],
  },
  {
    id: 'phy-造化万工体',
    name: '造化万工体',
    tier: '仙体',
    category: '生产',
    五行: '阳',
    subtitle: '生产',
    cost: 15,
    悟性: 38,
    根骨: 30,
    气感: 32,
    效果: [
      { name: '万工', value: '进行生产时，生产规则采用的对应技艺+30%' },
      { name: '造化', value: '首次成功生产任意配方时，对应技艺获得值+50%' },
    ],
    glyph: '阳',
    tags: ['生产', '阳'],
  },
  {
    id: 'phy-百炼筋骨',
    name: '百炼筋骨',
    tier: '灵体',
    category: '修炼',
    五行: '金',
    subtitle: '修炼',
    cost: 3,
    悟性: 14,
    根骨: 24,
    气感: 12,
    效果: [
      { name: '百炼', value: '修炼时，丹毒排除速度视为+10%' },
      { name: '强筋', value: '进行负重或角力判定时，根骨视为+2' },
    ],
    glyph: '金',
    tags: ['修炼', '金'],
  },
  {
    id: 'phy-夜照灵体',
    name: '夜照灵体',
    tier: '灵体',
    category: '修炼',
    五行: '阴',
    subtitle: '修炼',
    cost: 3,
    悟性: 19,
    根骨: 13,
    气感: 18,
    效果: [
      { name: '夜照', value: '夜间神识探查范围+15%' },
      { name: '吸月', value: '月夜修炼时，修为+10%' },
    ],
    glyph: '阴',
    tags: ['修炼', '阴'],
  },
  {
    id: 'phy-聚灵脉体',
    name: '聚灵脉体',
    tier: '灵体',
    category: '修炼',
    五行: '水',
    subtitle: '修炼',
    cost: 3,
    悟性: 17,
    根骨: 15,
    气感: 18,
    效果: [{ name: '聚灵周天', value: '修炼时，修为+10%' }],
    glyph: '水',
    tags: ['修炼', '水'],
  },
  {
    id: 'phy-药髓化真体',
    name: '药髓化真体',
    tier: '灵体',
    category: '修炼',
    五行: '木',
    subtitle: '修炼',
    cost: 3,
    悟性: 18,
    根骨: 17,
    气感: 15,
    效果: [
      { name: '药髓化真', value: '通过服丹获取修为时，修为+10%' },
      { name: '净药', value: '服丹时，丹毒增量-10%' },
    ],
    glyph: '木',
    tags: ['修炼', '木'],
  },
  {
    id: 'phy-合欢灵蕴体',
    name: '合欢灵蕴体',
    tier: '道体',
    category: '修炼',
    五行: '阴',
    subtitle: '修炼',
    cost: 9,
    悟性: 27,
    根骨: 21,
    气感: 27,
    效果: [
      { name: '合和', value: '通过双修获取修为时，修为+20%' },
      { name: '灵蕴', value: '失去元阴/元阳时，自身灵蕴+4' },
    ],
    glyph: '阴',
    tags: ['修炼', '阴'],
  },
  {
    id: 'phy-归元无漏体',
    name: '归元无漏体',
    tier: '道体',
    category: '修炼',
    五行: '土',
    subtitle: '修炼',
    cost: 9,
    悟性: 25,
    根骨: 27,
    气感: 23,
    效果: [
      { name: '归元', value: '修炼时，修为+15%' },
      { name: '无漏', value: '修炼时，丹毒排除速度+20%' },
    ],
    glyph: '土',
    tags: ['修炼', '土'],
  },
  {
    id: 'phy-吞灵化道体',
    name: '吞灵化道体',
    tier: '仙体',
    category: '修炼',
    五行: '混沌',
    subtitle: '修炼',
    cost: 15,
    悟性: 34,
    根骨: 34,
    气感: 32,
    效果: [{ name: '噬源', value: '通过夺灵获取修为时，修为+25%' }],
    glyph: '混沌',
    tags: ['修炼', '混沌'],
  },
  {
    id: 'phy-灵关通窍体',
    name: '灵关通窍体',
    tier: '灵体',
    category: '突破',
    五行: '阳',
    subtitle: '突破',
    cost: 3,
    悟性: 19,
    根骨: 14,
    气感: 17,
    效果: [{ name: '通关', value: '突破成功率+10%' }],
    glyph: '阳',
    tags: ['突破', '阳'],
  },
  {
    id: 'phy-万法归神体',
    name: '万法归神体',
    tier: '仙体',
    category: '突破',
    五行: '混沌',
    subtitle: '突破',
    cost: 15,
    悟性: 36,
    根骨: 30,
    气感: 34,
    效果: [{ name: '归神', value: '突破成功率+30%' }],
    glyph: '混沌',
    tags: ['突破', '混沌'],
  },
  {
    id: 'phy-tong-tou',
    name: '通透玲珑心',
    tier: '灵体',
    category: '领悟',
    五行: '水',
    subtitle: '领悟',
    cost: 3,
    悟性: 22,
    根骨: 14,
    气感: 14,
    效果: [{ name: '玲珑心窍', value: '进行领悟判定时，悟性+15%' }],
    glyph: '水',
    tags: ['领悟', '水'],
  },
  {
    id: 'phy-jian-ti',
    name: '先天剑体',
    tier: '灵体',
    category: '领悟',
    五行: '金',
    subtitle: '领悟',
    cost: 3,
    悟性: 17,
    根骨: 16,
    气感: 17,
    效果: [
      { name: '剑心', value: '领悟剑类功法时，悟性+15%' },
      { name: '剑鸣', value: '战斗中，装备剑类法宝进行攻击检定时，命中视为+1' },
    ],
    glyph: '金',
    tags: ['领悟', '金'],
  },
  {
    id: 'phy-da-luo',
    name: '大罗玲珑体',
    tier: '道体',
    category: '领悟',
    五行: '混沌',
    subtitle: '领悟',
    cost: 9,
    悟性: 28,
    根骨: 22,
    气感: 25,
    效果: [
      { name: '触类旁通', value: '进行领悟判定时，悟性+20%' },
      { name: '融会贯通', value: '领悟成功时，阶段收获与终末精进的技艺数值+20%' },
    ],
    glyph: '混沌',
    tags: ['领悟', '混沌'],
  },
  {
    id: 'phy-七窍闻道体',
    name: '七窍闻道体',
    tier: '道体',
    category: '领悟',
    五行: '木',
    subtitle: '领悟',
    cost: 9,
    悟性: 31,
    根骨: 19,
    气感: 25,
    效果: [
      { name: '闻道', value: '进行领悟判定时，悟性+20%' },
      { name: '闻一知十', value: '领悟成功时，阶段收获的技艺数值+25%' },
      { name: '七窍', value: '神识探查范围+15%' },
    ],
    glyph: '木',
    tags: ['领悟', '木'],
  },
  {
    id: 'phy-万劫兵胎',
    name: '万劫兵胎',
    tier: '道体',
    category: '领悟',
    五行: '金',
    subtitle: '领悟',
    cost: 9,
    悟性: 23,
    根骨: 30,
    气感: 22,
    效果: [
      { name: '兵主', value: '战斗中，装备法宝进行攻击时，攻击力视为+18%' },
      { name: '百兵通明', value: '领悟兵器类功法时，悟性+20%' },
      { name: '兵法归一', value: '领悟兵器类功法大成时，终末精进的技艺数值+25%' },
    ],
    glyph: '金',
    tags: ['领悟', '金'],
  },
  {
    id: 'phy-天心通明体',
    name: '天心通明体',
    tier: '道体',
    category: '领悟',
    五行: '阳',
    subtitle: '领悟',
    cost: 9,
    悟性: 32,
    根骨: 19,
    气感: 24,
    效果: [
      { name: '天心', value: '神识探查范围+20%' },
      { name: '通明', value: '领悟神识或阵法功法时，悟性+20%' },
      { name: '通神', value: '领悟神识或阵法功法大成时，终末精进的技艺数值+25%' },
    ],
    glyph: '阳',
    tags: ['领悟', '阳'],
  },
  {
    id: 'phy-hong-meng',
    name: '鸿蒙开天体',
    tier: '仙体',
    category: '领悟',
    五行: '混沌',
    subtitle: '领悟',
    cost: 15,
    悟性: 40,
    根骨: 30,
    气感: 30,
    效果: [
      { name: '万法初源', value: '修炼金、木、水、火或土属性心法时，修为+25%' },
      { name: '开天悟道', value: '进行领悟判定时，悟性+25%' },
      { name: '道果', value: '领悟成功时，阶段收获与终末精进的技艺数值+25%' },
    ],
    glyph: '混沌',
    tags: ['领悟', '混沌'],
  },
  {
    id: 'phy-沧浪灵体',
    name: '沧浪灵体',
    tier: '灵体',
    category: '综合',
    五行: '水',
    subtitle: '综合',
    cost: 3,
    悟性: 16,
    根骨: 16,
    气感: 18,
    效果: [
      { name: '纳流', value: '战斗中，使用水属性功法时，攻击力视为+12%' },
      { name: '润脉', value: '战斗外获得的气血恢复量+10%' },
    ],
    glyph: '水',
    tags: ['综合', '水'],
  },
  {
    id: 'phy-星砂灵体',
    name: '星砂灵体',
    tier: '灵体',
    category: '综合',
    五行: '混沌',
    subtitle: '综合',
    cost: 3,
    悟性: 17,
    根骨: 15,
    气感: 18,
    效果: [
      { name: '星引', value: '进行非战斗御物判定时，御物+10%' },
      { name: '星御', value: '战斗中，进行远程攻击伤害计算时，御物视为+10%' },
      { name: '省识', value: '战斗中，使用御物功法时，灵气消耗视为-10%' },
    ],
    glyph: '混沌',
    tags: ['综合', '混沌'],
  },
  {
    id: 'phy-药灵之体',
    name: '药灵之体',
    tier: '灵体',
    category: '综合',
    五行: '木',
    subtitle: '综合',
    cost: 3,
    悟性: 18,
    根骨: 16,
    气感: 16,
    效果: [
      { name: '识药', value: '进行炼丹或医术判定时，对应技艺+10%' },
      { name: '受药', value: '战斗中，使用丹药恢复气血时，气血恢复量视为+10%' },
    ],
    glyph: '木',
    tags: ['综合', '木'],
  },
  {
    id: 'phy-金磁灵躯',
    name: '金磁灵躯',
    tier: '灵体',
    category: '综合',
    五行: '金',
    subtitle: '综合',
    cost: 3,
    悟性: 15,
    根骨: 18,
    气感: 17,
    效果: [
      { name: '磁御', value: '进行非战斗御物判定时，御物+10%' },
      { name: '磁战', value: '战斗中，进行远程攻击伤害计算时，御物视为+10%' },
      { name: '引锋', value: '战斗中，使用金属法宝进行攻击检定时，命中视为+1' },
    ],
    glyph: '金',
    tags: ['综合', '金'],
  },
  {
    id: 'phy-曦光灵体',
    name: '曦光灵体',
    tier: '灵体',
    category: '综合',
    五行: '阳',
    subtitle: '综合',
    cost: 3,
    悟性: 18,
    根骨: 17,
    气感: 15,
    效果: [
      { name: '曦照', value: '日间修炼时，修为+10%' },
      { name: '暖脉', value: '战斗中，气血恢复量视为+10%' },
    ],
    glyph: '阳',
    tags: ['综合', '阳'],
  },
  {
    id: 'phy-灵犀心体',
    name: '灵犀心体',
    tier: '灵体',
    category: '综合',
    五行: '阳',
    subtitle: '综合',
    cost: 3,
    悟性: 21,
    根骨: 13,
    气感: 16,
    效果: [
      { name: '灵犀', value: '进行非战斗神识或御物判定时，对应技艺+10%' },
      { name: '识战', value: '战斗中，进行神识意图对抗时，神识视为+10%' },
      { name: '同调', value: '战斗中，与友方攻击同一目标时，命中视为+1' },
    ],
    glyph: '阳',
    tags: ['综合', '阳'],
  },
  {
    id: 'phy-玄黄灵体',
    name: '玄黄灵体',
    tier: '灵体',
    category: '综合',
    五行: '土',
    subtitle: '综合',
    cost: 3,
    悟性: 15,
    根骨: 21,
    气感: 14,
    效果: [
      { name: '玄黄承器', value: '进行炼器或阵法判定时，对应技艺+10%' },
      { name: '承压', value: '战斗中，受到近身攻击时，减免视为+10%' },
    ],
    glyph: '土',
    tags: ['综合', '土'],
  },
  {
    id: 'phy-huang-gu',
    name: '荒古圣体',
    tier: '道体',
    category: '综合',
    五行: '土',
    subtitle: '综合',
    cost: 9,
    悟性: 23,
    根骨: 27,
    气感: 25,
    效果: [
      { name: '愈战愈勇', value: '战斗中，气血低于50%时，攻击力视为+20%' },
      { name: '古血炼身', value: '修炼时，丹毒排除速度视为+15%' },
    ],
    glyph: '土',
    tags: ['综合', '土'],
  },
  {
    id: 'phy-tai-yin',
    name: '太阴炼形',
    tier: '道体',
    category: '综合',
    五行: '阴',
    subtitle: '综合',
    cost: 9,
    悟性: 27,
    根骨: 22,
    气感: 26,
    效果: [
      { name: '月炼', value: '月夜修炼时，修为+20%' },
      { name: '太阴', value: '战斗中，使用阴属性功法时，攻击力视为+15%' },
    ],
    glyph: '阴',
    tags: ['综合', '阴'],
  },
  {
    id: 'phy-tai-yang',
    name: '太阳真火体',
    tier: '道体',
    category: '综合',
    五行: '阳',
    subtitle: '综合',
    cost: 9,
    悟性: 25,
    根骨: 25,
    气感: 25,
    效果: [
      { name: '日炼', value: '日间修炼时，修为+20%' },
      { name: '破邪', value: '战斗中，攻击阴属性目标时，攻击力视为+15%' },
    ],
    glyph: '阳',
    tags: ['综合', '阳'],
  },
  {
    id: 'phy-九幽玄阴体',
    name: '九幽玄阴体',
    tier: '道体',
    category: '综合',
    五行: '阴',
    subtitle: '综合',
    cost: 9,
    悟性: 28,
    根骨: 21,
    气感: 26,
    效果: [
      { name: '九幽', value: '战斗中，使用阴属性功法时，攻击力视为+20%' },
      { name: '玄阴', value: '月夜修炼时，修为+15%' },
    ],
    glyph: '阴',
    tags: ['综合', '阴'],
  },
  {
    id: 'phy-南明离火体',
    name: '南明离火体',
    tier: '道体',
    category: '综合',
    五行: '火',
    subtitle: '综合',
    cost: 9,
    悟性: 26,
    根骨: 24,
    气感: 25,
    效果: [
      { name: '南明离火', value: '战斗中，使用火属性功法时，攻击力视为+20%' },
      { name: '丹器真焰', value: '进行炼丹或炼器判定时，火焰加值+20%' },
    ],
    glyph: '火',
    tags: ['综合', '火'],
  },
  {
    id: 'phy-jiu-tian',
    name: '九天玄女体',
    tier: '仙体',
    category: '综合',
    五行: '阳',
    subtitle: '综合',
    cost: 15,
    悟性: 36,
    根骨: 28,
    气感: 36,
    效果: [
      { name: '玄女神识', value: '战斗中，进行神识意图对抗时，神识视为+25%' },
      { name: '天工演阵', value: '战斗中，自身参与结成的阵法灵气容量视为+25%' },
      { name: '符阵通明', value: '进行制符或阵法判定时，对应技艺+25%' },
    ],
    glyph: '阳',
    tags: ['综合', '阳'],
  },
  {
    id: 'phy-zi-wei',
    name: '紫薇圣君体',
    tier: '仙体',
    category: '综合',
    五行: '金',
    subtitle: '综合',
    cost: 15,
    悟性: 32,
    根骨: 36,
    气感: 32,
    效果: [
      { name: '帝星', value: '获取修为时，修为+25%' },
      { name: '星命', value: '每自然日可重掷一次失败的非战斗判定，且必须接受第二次结果' },
    ],
    glyph: '金',
    tags: ['综合', '金'],
  },
  {
    id: 'phy-long-huang',
    name: '龙皇神体',
    tier: '仙体',
    category: '综合',
    五行: '阳',
    subtitle: '综合',
    cost: 15,
    悟性: 28,
    根骨: 42,
    气感: 30,
    效果: [
      { name: '龙力', value: '战斗中，使用徒手或近身攻击时，攻击力视为+25%' },
      { name: '龙威', value: '战斗中，面对同境及以下敌方灵兽时，敌方灵兽第一轮的命中视为-3' },
      { name: '御兽天成', value: '进行驯兽判定时，驯兽技艺+25%' },
    ],
    glyph: '阳',
    tags: ['综合', '阳'],
  },
  {
    id: 'phy-百兽同心体',
    name: '百兽同心体',
    tier: '灵体',
    category: '叙述',
    五行: '木',
    subtitle: '叙述',
    cost: 3,
    悟性: 16,
    根骨: 18,
    气感: 16,
    效果: [{ name: '兽缘', value: '野生兽类与灵兽天然亲近，野生灵兽不会主动发起攻击' }],
    glyph: '木',
    tags: ['叙述', '木'],
  },
  {
    id: 'phy-草木留声体',
    name: '草木留声体',
    tier: '灵体',
    category: '叙述',
    五行: '土',
    subtitle: '叙述',
    cost: 3,
    悟性: 19,
    根骨: 14,
    气感: 17,
    效果: [{ name: '草木留声', value: '可模糊地感知周围植物中蕴含的情绪，借此推测周边信息' }],
    glyph: '土',
    tags: ['叙述', '土'],
  },
  {
    id: 'phy-风语灵体',
    name: '风语灵体',
    tier: '灵体',
    category: '叙述',
    五行: '木',
    subtitle: '叙述',
    cost: 3,
    悟性: 18,
    根骨: 14,
    气感: 18,
    效果: [{ name: '风语', value: '可从风中听见附近强烈情绪形成的残响，用来模糊判断某处曾有争执、恐惧或欢庆' }],
    glyph: '木',
    tags: ['叙述', '木'],
  },
  {
    id: 'phy-烛影验心体',
    name: '烛影验心体',
    tier: '灵体',
    category: '叙述',
    五行: '火',
    subtitle: '叙述',
    cost: 3,
    悟性: 20,
    根骨: 14,
    气感: 16,
    效果: [{ name: '烛证', value: '能够模糊的感知他人的灵魂从而察觉他人的谎言；只能察觉谎言，不能得知真相' }],
    glyph: '火',
    tags: ['叙述', '火'],
  },
  {
    id: 'phy-镜月映心体',
    name: '镜月映心体',
    tier: '道体',
    category: '叙述',
    五行: '水',
    subtitle: '叙述',
    cost: 9,
    悟性: 30,
    根骨: 20,
    气感: 25,
    效果: [{ name: '镜月映心', value: '与他人长期对视时，能模糊地看见对方内心最难割舍的愿望，无读心效果' }],
    glyph: '水',
    tags: ['叙述', '水'],
  },
  {
    id: 'phy-太虚梦蝶体',
    name: '太虚梦蝶体',
    tier: '仙体',
    category: '叙述',
    五行: '混沌',
    subtitle: '叙述',
    cost: 15,
    悟性: 38,
    根骨: 28,
    气感: 34,
    效果: [{ name: '太虚梦蝶', value: '梦中可能看见过去、他人梦境边缘或未定未来，梦象允许失真' }],
    glyph: '混沌',
    tags: ['叙述', '混沌'],
  },
  {
    id: 'phy-照世真瞳体',
    name: '照世真瞳体',
    tier: '仙体',
    category: '叙述',
    五行: '阳',
    subtitle: '叙述',
    cost: 15,
    悟性: 38,
    根骨: 32,
    气感: 30,
    效果: [
      {
        name: '真瞳',
        value: '能够直接看穿易容、变化之术和作用于视觉的幻象，看到目标当前真实外貌；无法仅凭外貌获知其姓名与经历',
      },
    ],
    glyph: '阳',
    tags: ['叙述', '阳'],
  },
  {
    id: 'phy-暖玉春肌体',
    name: '暖玉春肌体',
    tier: '灵体',
    category: 'NSFW',
    五行: '火',
    subtitle: 'NSFW',
    cost: 3,
    悟性: 17,
    根骨: 18,
    气感: 15,
    效果: [{ name: '暖玉春肌', value: '情动时会散出体香,使他人能够察觉自身欲望的变化' }],
    glyph: '火',
    tags: ['NSFW', '火'],
  },
  {
    id: 'phy-阴阳回响体',
    name: '阴阳回响体',
    tier: '灵体',
    category: 'NSFW',
    五行: '水',
    subtitle: 'NSFW',
    cost: 3,
    悟性: 18,
    根骨: 14,
    气感: 18,
    效果: [{ name: '回响', value: '双修时对方承受双倍快感' }],
    glyph: '水',
    tags: ['NSFW', '水'],
  },
  {
    id: 'phy-天香蜜髓体',
    name: '天香蜜髓体',
    tier: '道体',
    category: 'NSFW',
    五行: '木',
    subtitle: 'NSFW',
    cost: 9,
    悟性: 27,
    根骨: 22,
    气感: 26,
    效果: [
      { name: '蜜髓灵蕴', value: '失去元阴/元阳时，自身灵蕴+4' },
      { name: '天香蜜髓', value: '体液会带有清甜灵香' },
    ],
    glyph: '木',
    tags: ['NSFW', '木'],
  },
  {
    id: 'phy-阴阳交泰体',
    name: '阴阳交泰体',
    tier: '道体',
    category: 'NSFW',
    五行: '阴',
    subtitle: 'NSFW',
    cost: 9,
    悟性: 25,
    根骨: 24,
    气感: 26,
    效果: [
      { name: '阴阳交泰', value: '双修获取修为+20%' },
      { name: '灵液', value: '他人吃下自己的任何体液时可增加修为，对自身无效' },
    ],
    glyph: '阴',
    tags: ['NSFW', '阴'],
  },
  {
    id: 'phy-极乐天魔体',
    name: '极乐天魔体',
    tier: '仙体',
    category: 'NSFW',
    五行: '混沌',
    subtitle: 'NSFW',
    cost: 15,
    悟性: 36,
    根骨: 30,
    气感: 34,
    效果: [
      { name: '天魔采真', value: '双修获取修为+30%' },
      { name: '极乐天魔', value: '双修时可使附近他人的感官共享，同步感受' },
    ],
    glyph: '混沌',
    tags: ['NSFW', '混沌'],
  },
  {
    id: 'phy-阴阳无相体',
    name: '阴阳无相体',
    tier: '仙体',
    category: 'NSFW',
    五行: '混沌',
    subtitle: 'NSFW',
    cost: 15,
    悟性: 38,
    根骨: 30,
    气感: 32,
    效果: [
      { name: '无相合道', value: '双修获取修为+30%' },
      { name: '阴阳无相', value: '亲密行为中可随意改变自身性器的形态与性征，使其适配双方选择并保持真实触感' },
    ],
    glyph: '混沌',
    tags: ['NSFW', '混沌'],
  },
];

export const findPhysique = (id: string | null): PhysiqueOption | undefined =>
  id ? physiques.find(p => p.id === id) : undefined;

export const physiquesByTier = (tier: PhysiqueTier): PhysiqueOption[] => physiques.filter(p => p.tier === tier);

export const physiqueCategoriesByTier = (tier: PhysiqueTier): PhysiqueCategory[] => {
  const available = new Set(physiquesByTier(tier).map(p => p.category));
  return PHYSIQUE_CATEGORIES.filter(category => available.has(category));
};

export const physiquesByTierAndCategory = (tier: PhysiqueTier, category: PhysiqueCategory | null): PhysiqueOption[] =>
  physiques.filter(p => p.tier === tier && (category === null || p.category === category));

export function emptyPhysiqueChoice(): PhysiqueChoice {
  return makeDefaultPhysiqueChoice('凡体');
}

/** 切换 tier 时生成默认（自拟）三维：尽量均匀分配 S */
export function makeDefaultPhysiqueChoice(tier: PhysiqueTier): PhysiqueChoice {
  const S = PHYSIQUE_TIER_S[tier];
  const a = Math.floor(S / 3);
  const b = Math.floor(S / 3);
  const c = S - a - b;
  return {
    tier,
    presetId: null,
    customName: '',
    customEffects: tier === '凡体' ? [] : [{ name: '', value: '' }],
    custom悟性: a,
    custom根骨: b,
    custom气感: c,
  };
}

export function normalizePhysiqueChoice(raw: any): PhysiqueChoice {
  const empty = emptyPhysiqueChoice();
  if (!raw || typeof raw !== 'object') return empty;
  const tier: PhysiqueTier = (PHYSIQUE_TIERS as readonly string[]).includes(raw.tier)
    ? (raw.tier as PhysiqueTier)
    : '凡体';
  const fallback = makeDefaultPhysiqueChoice(tier);
  // 兼容旧持久化字段：customEffectName/customEffectValue → customEffects[]
  let customEffects: PhysiqueEffect[];
  if (Array.isArray(raw.customEffects)) {
    customEffects = raw.customEffects
      .filter((e: any) => e && typeof e === 'object')
      .map((e: any) => ({
        name: typeof e.name === 'string' ? e.name : '',
        value: typeof e.value === 'string' ? e.value : '',
      }));
  } else if (typeof raw.customEffectName === 'string' || typeof raw.customEffectValue === 'string') {
    customEffects = [
      {
        name: typeof raw.customEffectName === 'string' ? raw.customEffectName : '',
        value: typeof raw.customEffectValue === 'string' ? raw.customEffectValue : '',
      },
    ];
  } else {
    customEffects = fallback.customEffects;
  }
  const presetId = typeof raw.presetId === 'string' && findPhysique(raw.presetId)?.tier === tier ? raw.presetId : null;
  return {
    tier,
    presetId,
    customName: typeof raw.customName === 'string' ? raw.customName : '',
    customEffects,
    custom悟性: Number.isFinite(raw.custom悟性) ? raw.custom悟性 : fallback.custom悟性,
    custom根骨: Number.isFinite(raw.custom根骨) ? raw.custom根骨 : fallback.custom根骨,
    custom气感: Number.isFinite(raw.custom气感) ? raw.custom气感 : fallback.custom气感,
  };
}

export function physiqueCost(choice: PhysiqueChoice): number {
  return PHYSIQUE_TIER_COST[choice.tier];
}

/** 自拟三维当前总和 */
export function customPhysiqueSum(choice: PhysiqueChoice): number {
  return (choice.custom悟性 || 0) + (choice.custom根骨 || 0) + (choice.custom气感 || 0);
}

export interface ResolvedPhysique {
  name: string;
  tier: PhysiqueTier;
  desc: string;
  悟性: number;
  根骨: number;
  气感: number;
  /** 已规范化的效果数组 */
  效果s: PhysiqueEffect[];
}

export function physiqueResolved(choice: PhysiqueChoice): ResolvedPhysique {
  if (choice.presetId) {
    const p = findPhysique(choice.presetId);
    if (p) {
      return {
        name: p.name,
        tier: p.tier,
        desc: p.desc || '',
        悟性: p.悟性,
        根骨: p.根骨,
        气感: p.气感,
        效果s: p.效果 ? p.效果.map(effect => ({ ...effect })) : [],
      };
    }
  }
  const name = choice.customName.trim() || `${choice.tier}（自创）`;
  const 效果s: PhysiqueEffect[] =
    choice.tier === '凡体'
      ? []
      : choice.customEffects
          .map(effect => ({ name: effect.name.trim(), value: effect.value.trim() }))
          .filter(effect => effect.name);
  return {
    name,
    tier: choice.tier,
    desc: '玩家自创之体。',
    悟性: choice.custom悟性,
    根骨: choice.custom根骨,
    气感: choice.custom气感,
    效果s,
  };
}

export function isPhysiqueChoiceValid(choice: PhysiqueChoice): boolean {
  if (choice.presetId) {
    return !!findPhysique(choice.presetId);
  }
  if (!choice.customName.trim()) return false;
  if (choice.tier !== '凡体') {
    const hasNamedEffect = choice.customEffects.some(effect => effect.name.trim() !== '');
    if (!hasNamedEffect) return false;
  }
  if (customPhysiqueSum(choice) !== PHYSIQUE_TIER_S[choice.tier]) return false;
  if (choice.custom悟性 < 1 || choice.custom根骨 < 1 || choice.custom气感 < 1) return false;
  return true;
}
